//auth types
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_FALLIDO = 'REGISTRO_FALLIDO'
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA'
export const INICIO_EXITOSO = 'INICIO_EXITOSO'
export const INICIO_FALLIDO = 'INICIO_FALLIDO'
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO'
export const CERRAR_SESION = 'CERRAR_SESION'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

//types de archivos 
export const SUBIR_ARCHIVO_EXITO = 'SUBIR_ARCHIVO_EXITO'
export const SUBIR_ARCHIVO_ERROR = 'SUBIR_ARCHIVO_ERROR'
export const SUBIR_ARCHIVO = 'SUBIR_ARCHIVO'

export const CREAR_ENLACE_EXITO = 'CREAR_ENLACE_EXITO'
export const CREAR_ENLACE_ERROR = 'CREAR_ENLACE_ERROR'

export const LIMPIAR_STATE = 'LIMPIAR_STATE'