//auth types
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_FALLIDO = 'REGISTRO_FALLIDO'
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA'
export const INICIO_EXITOSO = 'INICIO_EXITOSO'
export const INICIO_FALLIDO = 'INICIO_FALLIDO'
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO'
export const CERRAR_SESION = 'CERRAR_SESION'